apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: roboshop
    tier: db
    environment: dev
  clusterIP: None
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: roboshop
    tier: db
    environment: dev
spec:
  serviceName: "mongodb"
  replicas: 3
  selector:
    matchLabels:
      app: roboshop
      tier: db
      environment: dev
  template:
    metadata:
      labels:
        app: roboshop
        tier: db
        environment: dev
    spec:
      containers:
      - name: mongodb
        image: pavankg2101/mongodb:v1.0
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata: 
      name: mongodb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi


