apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
    tier: app
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      tier: app
      environment: dev
  template:
    metadata:
      labels:
        app: payment
        tier: app
        environment: dev
    spec:
      containers:
      - name: payment
        image: pavankg2101/payment:v1.0
        envFrom:
        - configMapRef:
            name: payment-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
    tier: app
    environment: dev
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
