apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # keep true in double quotes
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
    tier: db
    environment: dev
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: db
      environment: dev
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        environment: dev
    spec:
      containers:
      - name: mysql
        image: pavankg2101/mysql:v1.0
        envFrom:
        - configMapRef:
            name: mysql-config
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata: 
      name: mysql
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
    tier: db
    environment: dev
  clusterIP: None
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
