apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: roboshop
    tier: db
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roboshop
      tier: db
      environment: dev
  template:
    metadata:
      labels:
        app: roboshop
        tier: db
        environment: dev
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:4.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: roboshop
    tier: db
    environment: dev
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
