apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  MONGO: "true"
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
    tier: app
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: app
      environment: dev
  template:
    metadata:
      labels:
        app: user
        tier: app
        environment: dev
    spec:
      containers:
      - name: user
        image: pavankg2101/user:v1.0
        envFrom:
        - configMapRef:
            name: user-config
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
    tier: app
    environment: dev
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
